spring.application.name=airBnbApp

#DB configs
spring.datasource.url=jdbc:postgresql://ep-quiet-wind-ao6b6c5d.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.username=neondb_owner
spring.datasource.password=npg_qCR0H3BnwhFA